[package]
name = "json2tests"
description = "Macro to generate your Rust tests from a provided JSON file"
version = "0.2.0"
edition = "2024"
authors = ["niri81"]
homepage = "https://github.com/niri81/json2tests-rs/"
repository = "https://github.com/niri81/json2tests-rs/"
license-file = "LICENSE"
readme = "README.md"
categories = ["development-tools::testing"]
keywords = ["testing", "json", "test-generation"]

[lib]
proc-macro = true

[dependencies]
anyhow = "1.0.100"
assert-json-diff = "2.0.2"
quote = "1.0.41"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
syn = "2.0.106"
uuid = "1.18.1"
